# Generated by Django 2.1.7 on 2019-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.FileField(null=True, upload_to='blog/%Y/%m/%d/'),
        ),
    ]
