# Generated by Django 2.1.7 on 2019-03-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.FileField(null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
