# Generated by Django 2.1.7 on 2019-03-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190301_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(null=True, upload_to='%Y/%m/%d/'),
        ),
    ]
